public class Main{
    public static void main(String[] args) {
        try{
            int a = 10/0;
        }catch (ArithmeticException e){
            System.out.println("Caught an exception" + e);
        }finally {
            System.out.println("Finaally block executed");
        }
    }
}
